version: "3"
services:
    db:
        image: postgres:13
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
        volumes:
            - "./.dockerdata/postgres:/var/lib/postgresql/data"
